---
title: Terremoto Centro Italia
timezone: Europe/Rome
collections:
  posts:
    title: Posts
    output: true
  storie:
    title: Storie
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    social-share: true
- scope:
    path: ''
  values:
    layout: page
    show-avatar: true
url: http://terremotocentroitalia.info
description: Un progetto per informare sul terremoto del 24 Agosto 2016
navbar-links:
  Aggiornamenti:
  - Bollettino: bollettino/
  - Blog: post/
  - Storie: storie/
  Hai bisogno?:
  - Segnala: aiuto/
  - Alloggi: alloggi/
  - Vittime: vittime/
  - Link utili: link_utili/
  Mappe: mappe/
  Vuoi donare?:
  - Risorse disponibili: risorse-disponibili/
  - Raccolta Fondi: fondi/
  - Fabbisogni: fabbisogni/
  Il Progetto:
  - About: about/
  - WIKI: https://github.com/emergenzeHack/terremotocentro/wiki" target="_blank
  - Press: press/
  - Canali di Comunicazione: canali/
avatar: "/images/noun_8681.png"
author:
  name: TerremotoCentroItalia
  facebook: groups/1758670357733881/
  github: emergenzeHack/terremotocentro
  twitter: terremotocentro
  linkedin: 
  xing: 
  stackoverflow: 
  instagram: terremotocentro
  youtube: yourlink
  rss: https://emergenzehack.github.io/terremotocentro/feed.xml
  telegram: https://telegram.me/terremotocentroitalia
  medium: https://medium.com/terremotocentroitalia
  archiveorg: https://archive.org/details/@terremotocentroita
footer-links-active:
  rss: true
  facebook: true
  email: false
  twitter: true
  github: true
  linkedin: false
  xing: false
  stackoverflow: false
  instagram: true
  youtube: false
  telegram: true
  medium: true
  archiveorg: true
share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: false
disqus: terremotocentroitalia
google_analytics: UA-47474515-3
markdown: kramdown
highlighter: rouge
permalink: "/:year-:month-:day-:title/"
paginate: 5
kramdown:
  input: GFM
link-tags: false
exclude:
- vendor
prose:
  rooturl: _posts
  media: img
  ignore:
  - 404.html
  - LICENSE
  - feed.xml
  - _config.yml
  - "/_layouts"
  - "/_includes"
  - "/css"
  - "/img"
  - "/js"
  - "/scripts"
  - "/external"
  metadata:
    _posts:
    - name: layout
      field:
        element: hidden
        value: post
    - name: title
      field:
        element: text
        label: Post title
        placeholder: Title
        alterable: true
    - name: subtitle
      field:
        element: textarea
        label: Subtitle
        placeholder: A description of your post.
        alterable: true
    - name: date
      field:
        element: text
        label: Date
        help: Enter date of post.
        placeholder: yyyy-mm-dd
        alterable: true
    - name: published
      field:
        element: checkbox
        label: Publish
        help: Check to publish post, uncheck to hide.
gems:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
